INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) VALUES ('user','password',TRUE);
INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) VALUES ('admin','admin',TRUE);
INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) VALUES ('apollo','apollo',TRUE);
INSERT INTO USERS(USERNAME,PASSWORD,ENABLED) VALUES ('java','java',TRUE);

INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES ('user','ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES ('admin','ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES ('apollo','ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES ('java','ROLE_USER');


INSERT INTO BLOGPOST (CONTENT,DRAFT,PUBLISHDATE,TITLE,USER_ID)
VALUES ('Test conntent Spring Mvc',false,NOW(),'test',1);
